name: Merge Example

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Navigate to project directory
        run: cd "github-action-angular"

      - name: Install dependencies
        run: npm install

      - name: Linting and testing
        run: |
          npm run lint
          npm run test